source "https://rubygems.org"

gem "middleman", "~>3.0.11"
gem "middleman-livereload"
gem "middleman-deploy"
gem "middleman-blog"
gem "middleman-syntax"
gem "builder"
gem "haml"
gem "sass"
gem "bootstrap-sass", "~> 2.3.2"
gem "redcarpet"
gem "nokogiri"
